MvcStore/MvcStore/Models/AccountModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Globalization;
using System.Web.Security;

namespace MvcStore.Models
{
    public class UsersContext : DbContext
    {
        public UsersContext()
            : base("DefaultConnection")
        {
        }

        public DbSet<UserProfile> UserProfiles { get; set; }
    }

    [Table("UserProfile")]
    public class UserProfile
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }
        public string UserName { get; set; }
    }

    public class RegisterExternalLoginModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        public string ExternalLoginData { get; set; }
    }

    public class LocalPasswordModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ExternalLogin
    {
        public string Provider { get; set; }
        public string ProviderDisplayName { get; set; }
        public string ProviderUserId { get; set; }
    }
}

MvcStore/MvcStore/Models/Brand.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcStore.Models
{
    public class Brand
    {
        public int BrandId { get; set; }

        [Required(ErrorMessage = "Brand Name is required")]
        [StringLength(50),MinLength(3)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; } 

        public List<Model> Models { get; set; }

     
    }
}

MvcStore/MvcStore/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStore.Models;

namespace MvcStore.Controllers
{
    //[Authorize(Roles = "Administrator")]
    public class ModelController : Controller
    {
        private CopierStoreEntities db = new CopierStoreEntities();

        //
        // GET: /Model/

        public ActionResult Index()
        {
            var models = db.Models.Include(m => m.Brand).Include(m => m.Toner).Include(m => m.Supplier);
            return View(models.ToList());
        }

        //
        // GET: /Model/Details/5

        public ActionResult Details(int id = 0)
        {
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        //
        // GET: /Model/Create

        public ActionResult Create()
        {
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name");
            ViewBag.TonerId = new SelectList(db.Toners, "TonerId", "Name");
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "Name");
            return View();
        }

        //
        // POST: /Model/Create

        [HttpPost]
        public ActionResult Create(Model model)
        {
            if (ModelState.IsValid)
            {
                db.Models.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name", model.BrandId);
            ViewBag.TonerId = new SelectList(db.Toners, "TonerId", "Name", model.TonerId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "Name", model.SupplierId);
            return View(model);
        }

        //
        // GET: /Model/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name", model.BrandId);
            ViewBag.TonerId = new SelectList(db.Toners, "TonerId", "Name", model.TonerId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "Name", model.SupplierId);
            return View(model);
        }

        //
        // POST: /Model/Edit/5

        [HttpPost]
        public ActionResult Edit(Model model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name", model.BrandId);
            ViewBag.TonerId = new SelectList(db.Toners, "TonerId", "Name", model.TonerId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "Name", model.SupplierId);
            return View(model);
        }

        //
        // GET: /Model/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        //
        // POST: /Model/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Model model = db.Models.Find(id);
            db.Models.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcStore/MvcStore/Controllers/StoreManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Objects;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using MvcStore.Models;


namespace MvcStore.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class StoreManagerController : Controller
    {
        private CopierStoreEntities db = new CopierStoreEntities();

        //
        // GET: /StoreManager/

        public ViewResult Index()
        {
            var models = db.Models.Include(m => m.Brand).Include(m => m.Toner).Include(m => m.Supplier);
            return View(models.ToList());
        }

        //
        // GET: /StoreManager/Details/5

        public ViewResult Details(int id)
        {
            Model model = db.Models.Find(id);
            return View(model);
        }

        //
        // GET: /StoreManager/Create

        public ActionResult Create()
        {
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name");
            ViewBag.TonerId = new SelectList(db.Toners, "TonerId", "Name");
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "Name");
            return View();
        }

        //
        // POST: /StoreManager/Create

        [HttpPost]
        public ActionResult Create(Model model)
        {
            if (ModelState.IsValid)
            {
                db.Models.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name", model.BrandId);
            ViewBag.TonerId = new SelectList(db.Toners, "TonerId", "Name", model.TonerId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "Name", model.SupplierId);
            return View(model);
        }

        //
        // GET: /StoreManager/Edit/5

        public ActionResult Edit(int id)
        {
            Model model = db.Models.Find(id);
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name", model.BrandId);
            ViewBag.TonerId = new SelectList(db.Toners, "TonerId", "Name", model.TonerId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "Name", model.SupplierId);
            return View(model);
        }

        //
        // POST: /StoreManager/Edit/5
        Object obj;

        [HttpPost]
        public ActionResult Edit(Model model)
        {
            if (ModelState.IsValid)
            {

                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");


            }
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name", model.BrandId);
            ViewBag.TonerId = new SelectList(db.Toners, "TonerId", "Name", model.TonerId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "Name", model.SupplierId);
            return View(model);
        }

        //
        // GET: /StoreManager/Delete/5

        public ActionResult Delete(int id)
        {
            Model model = db.Models.Find(id);
            return View(model);
        }

        //
        // POST: /StoreManager/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Model model = db.Models.Find(id);
            db.Models.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult Import()
        {
            return View();
        }

        public ActionResult Success()
        {
            return View();
        }

        public ActionResult Error()
        {
            return View();
        }

        public ActionResult EntryView()
        { 
           return View();
        }

        public ActionResult Importexcel()
        {
            if (Request.Files["FileUpload1"].ContentLength > 0)
            {
                string extension = System.IO.Path.GetExtension(Request.Files["FileUpload1"].FileName);
                string path1 = string.Format("{0}/{1}", Server.MapPath("~/Content/UploadedFolder"), Request.Files["FileUpload1"].FileName);
                if (System.IO.File.Exists(path1))
                    System.IO.File.Delete(path1);

                string sqlConnectionString = @"Data Source=SHAHRIAR\SQLEXPRESS;Database=MvcStore.Models.CopierStoreEntities;Trusted_Connection=true;Persist Security Info=True";

                Request.Files["FileUpload1"].SaveAs(path1);


                string excelConnectionString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + path1 + ";Extended Properties=Excel 12.0;Persist Security Info=False";

                OleDbConnection excelConnection = new OleDbConnection(excelConnectionString);
                OleDbCommand cmd = new OleDbCommand("Select * from [Sheet1$]", excelConnection);
                excelConnection.Open();
                OleDbDataReader dReader;
                dReader = cmd.ExecuteReader();

                SqlBulkCopy sqlBulk = new SqlBulkCopy(sqlConnectionString);
                sqlBulk.DestinationTableName = "Models";
                sqlBulk.WriteToServer(dReader);
                excelConnection.Close();

                return RedirectToAction("Success");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        public ActionResult ImportTonerexcel()
        {
            if (Request.Files["FileUpload2"].ContentLength > 0)
            {
                string extension = System.IO.Path.GetExtension(Request.Files["FileUpload2"].FileName);
                string path1 = string.Format("{0}/{1}", Server.MapPath("~/Content/UploadedFolder"), Request.Files["FileUpload2"].FileName);
                if (System.IO.File.Exists(path1))
                    System.IO.File.Delete(path1);

                string sqlConnectionString = @"Data Source=SHAHRIAR\SQLEXPRESS;Database=MvcStore.Models.CopierStoreEntities;Trusted_Connection=true;Persist Security Info=True";

                Request.Files["FileUpload2"].SaveAs(path1);


                string excelConnectionString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + path1 + ";Extended Properties=Excel 12.0;Persist Security Info=False";

                OleDbConnection excelConnection = new OleDbConnection(excelConnectionString);
                OleDbCommand cmd = new OleDbCommand("Select * from [Sheet2$]", excelConnection);
                excelConnection.Open();
                OleDbDataReader dReader;
                dReader = cmd.ExecuteReader();

                SqlBulkCopy sqlBulk = new SqlBulkCopy(sqlConnectionString);
                sqlBulk.DestinationTableName = "Toners";
                sqlBulk.WriteToServer(dReader);
                excelConnection.Close();

                return RedirectToAction("Success");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        [ChildActionOnly]
        public ActionResult AdminMenu()
        {
            return PartialView();
        }

        /*
          MvcStore.Models.CopierStoreEntities db=new MvcStore.Models.CopierStoreEntities();
    var dbdata = from c in db.Models select new {c.Title ,c.Price};
    var myChart = new Chart(width:1000, height: 800)
   .AddTitle("Product Sales")
   .AddSeries(chartType: "Pie",
      xValue: dbdata, xField: "Title",
      yValues: dbdata, yFields: "Price")
   .Write();
         */

        public ActionResult CustomerView()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcStore/MvcStore/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStore.Models;

namespace MvcStore.Controllers
{
    public class UserController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /User/

        public ActionResult Index()
        {
            return View(db.UserProfiles.ToList());
        }

        //
        // GET: /User/Details/5

        public ActionResult Details(int id = 0)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

      
        //
        // GET: /User/Edit/5

        public ActionResult Edit(int id = 0)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // POST: /User/Edit/5

        [HttpPost]
        public ActionResult Edit(UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userprofile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userprofile);
        }

        //
        // GET: /User/Delete/5

        public ActionResult Delete(int id = 0)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // POST: /User/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            db.UserProfiles.Remove(userprofile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcStore/MvcStore/Views/Model/Create.cshtml
@model MvcStore.Models.Model

@{
    ViewBag.Title = "Create";

    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
    {
        Text = "New",
        Value = "New",
        Selected = true
    });
    listItems.Add(new SelectListItem
    {
        Text = "Old",
        Value = "Old"

    });

    List<SelectListItem> typeListItems = new List<SelectListItem>();
    typeListItems.Add(new SelectListItem
    {
        Text = "Toner base Cartidge",
        Value = "Toner base Cartidge",
        Selected = true
    });
    typeListItems.Add(new SelectListItem
    {
        Text = "Toner ,Developer and Drum base Cartidge",
        Value = "Toner ,Developer and Drum base Cartidge"

    });
    typeListItems.Add(new SelectListItem
    {
        Text = "Developer base Cartidge",
        Value = "Developer base Cartidge"
    });
    typeListItems.Add(new SelectListItem
    {
        Text = "Drum base Cartidge",
        Value = "Drum base Cartidge"

    });
    
}


<h2>Add Product</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Model</legend>
        <table>
            <tr>
                <td>@Html.LabelFor(model => model.BrandId, "Brand")</td>
                <td>@Html.DropDownList("BrandId", String.Empty)
                    @Html.ValidationMessageFor(model => model.BrandId)

                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.SupplierId, "Supplier")</td>
                <td>
                    @Html.DropDownList("SupplierId", String.Empty)
                    @Html.ValidationMessageFor(model => model.SupplierId)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.TonerId, "Toner ")</td>
                <td>@Html.DropDownList("TonerId", String.Empty)
                    @Html.ValidationMessageFor(model => model.TonerId)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.ProductName)</td>
                <td>
                    @Html.EditorFor(model => model.ProductName)
                    @Html.ValidationMessageFor(model => model.ProductName)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.CompatibleModel)</td>

                <td>
                    @Html.TextAreaFor(model => model.CompatibleModel, new { @style = "resize:none; width:309px; height:150px;"})
                    @Html.ValidationMessageFor(model => model.CompatibleModel)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Manufacturer)</td>
                <td>

                    @Html.EditorFor(model => model.Manufacturer)
                    @Html.ValidationMessageFor(model => model.Manufacturer)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.CountryOfOrigin)</td>
                <td>

                    @Html.EditorFor(model => model.CountryOfOrigin)
                    @Html.ValidationMessageFor(model => model.CountryOfOrigin)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Status)</td>
                <td>

                    @Html.DropDownListFor(model => model.Status, listItems, new { @style="width:309px"})
                    @Html.ValidationMessageFor(model => model.Status)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Type)</td>
                <td>

                    @Html.DropDownListFor(model => model.Type, typeListItems, new { @style="width:309px"})
                    @Html.ValidationMessageFor(model => model.Type)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Packing)</td>
                <td>

                    @Html.EditorFor(model => model.Packing)
                    @Html.ValidationMessageFor(model => model.Packing)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Delivery)</td>
                <td>

                    @Html.EditorFor(model => model.Delivery)
                    @Html.ValidationMessageFor(model => model.Delivery)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Shipping)</td>
                <td>

                    @Html.EditorFor(model => model.Shipping)
                    @Html.ValidationMessageFor(model => model.Shipping)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Parts)</td>
                <td>

                    @Html.EditorFor(model => model.Parts)
                    @Html.ValidationMessageFor(model => model.Parts)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.PagePerToner)</td>
                <td>

                    @Html.EditorFor(model => model.PagePerToner)
                    @Html.ValidationMessageFor(model => model.PagePerToner)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Price)</td>
                <td>

                    @Html.EditorFor(model => model.Price)
                    @Html.ValidationMessageFor(model => model.Price)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.ModelUrl)</td>
                <td>

                    @Html.EditorFor(model => model.ModelUrl)
                    @Html.ValidationMessageFor(model => model.ModelUrl)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.ModelZoomUrl)</td>
                <td>

                    @Html.EditorFor(model => model.ModelUrl)
                    @Html.ValidationMessageFor(model => model.ModelZoomUrl)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.ModelUrl)</td>
                <td>

                    @Html.EditorFor(model => model.ModelSmallUrl)
                    @Html.ValidationMessageFor(model => model.ModelSmallUrl)
                </td>
            </tr>
        </table>

        <p>
            <input class="btn btn-warning" type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcStore/MvcStore/Views/Model/Delete.cshtml
@model MvcStore.Models.Model

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Confirmation</h2>

<h3>Are you sure you want to delete <strong>@Model.ProductName</strong>?</h3>

@using (Html.BeginForm()) {
    <p>
        <input class="btn btn-warning" type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcStore/MvcStore/Views/Model/Details.cshtml
@model MvcStore.Models.Model

@{
    ViewBag.Title = "Details";
}

<h2>Details of @Html.DisplayFor(model => model.ProductName)</h2>

<fieldset>
    <legend>Model</legend>
    <table class="tablesorter">
    <thead>
        <th>Topic</th>
        <th>Details</th>
    </thead>
    <tbody>
    <tr>
        <td>Brand</td>
        <td>@Html.DisplayFor(model => model.Brand.Name)</td>
    </tr>
    <tr>
        <td>Supplier</td>
        <td>@Html.DisplayFor(model => model.Supplier.Name)</td>
    </tr>
    <tr>
        <td>Toner</td>
        <td>@Html.DisplayFor(model => model.Toner.Name)</td>
    </tr>
       <tr>
        <td>Title</td>
        <td>@Html.DisplayFor(model => model.ProductName)</td>
    </tr>
    <tr>
        <td>Compitable Products</td>
        <td>@Html.DisplayFor(model => model.CompatibleModel)</td>
    </tr>
    <tr>
        <td>Manufacturer</td>
        <td>@Html.DisplayFor(model => model.Manufacturer)</td>
    </tr> 
       <tr>
        <td>Origin</td>
        <td>@Html.DisplayFor(model => model.CountryOfOrigin)</td>
    </tr>
    <tr>
        <td>Status</td>
        <td>@Html.DisplayFor(model => model.Status)</td>
    </tr>
    <tr>
        <td>Type</td>
        <td>@Html.DisplayFor(model => model.Type)</td>
    </tr>
       <tr>
        <td>Packaging</td>
        <td>@Html.DisplayFor(model => model.Packing)</td>
    </tr>
    <tr>
        <td>Delivery</td>
        <td>@Html.DisplayFor(model => model.Delivery)</td>
    </tr>
    <tr>
        <td>Shipping</td>
        <td>@Html.DisplayFor(model => model.Shipping)</td>
    </tr>
       <tr>
        <td>Parts</td>
        <td>@Html.DisplayFor(model => model.Parts)</td>
    </tr>
    <tr>
        <td>Page/Toner</td>
        <td>@Html.DisplayFor(model => model.PagePerToner)</td>
    </tr>
    <tr>
        <td>Price</td>
        <td>@Html.DisplayFor(model => model.Price)</td>
    </tr>
    </tbody>
</table>

</fieldset>
 
<br /> 
  
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ModelId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcStore/MvcStore/Views/Model/Index.cshtml
@model IEnumerable<MvcStore.Models.Model>

@{
    ViewBag.Title = "Index";
}


<div class="container-fluid">
    <div class="row-fluid">

        <div class="span2">
            @Html.Partial("~/Views/Model/ModelMenu.cshtml")
        </div>

        <div class="span10">

            <p>
                @Html.ActionLink("Create New", "Create")
            </p>
            
                <table class="tablesorter">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Brand.Name)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.ProductName)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.CountryOfOrigin)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Packing)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.PagePerToner)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Price)
                        </th>

                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Brand.Name)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.ProductName)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.CountryOfOrigin)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Packing)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.PagePerToner)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>

                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.ModelId }) |
                            @Html.ActionLink("Details", "Details", new { id = item.ModelId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.ModelId })
                            </td>
                        </tr>
                }

                </table>
        </div>
    </div>
</div>

MvcStore/MvcStore/Views/Model/ModelMenu.cshtml
@{
    ViewBag.Title = "BrandMenu";
}

<ul class="nav nav-tabs nav-stacked">
    <li>@Html.ActionLink("Store Manager", "Index", "StoreManager")</li>
    <li>@Html.ActionLink("Brand", "Index", "Brand")</li>
    <li>@Html.ActionLink("Cartidage", "Index", "Toner")</li>
    <li>@Html.ActionLink("Supplier", "Index", "Supplier")</li>
    <li>@Html.ActionLink("Users", "Index", "User")</li>
</ul>