MvcStore/MvcStore/Models/Brand.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcStore.Models
{
    public class Brand
    {
        public int BrandId { get; set; }

        [Required(ErrorMessage = "Brand Name is required")]
        [StringLength(50),MinLength(3)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; } 

        public List<Model> Models { get; set; }

     
    }
}

MvcStore/MvcStore/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStore.Models;

namespace MvcStore.Controllers
{
   // [Authorize(Roles = "Administrator")]
    public class BrandController : Controller
    {
        private CopierStoreEntities db = new CopierStoreEntities();

        public ActionResult Index()
        {
            return View(db.Brands.ToList());
        }

        //
        // GET: /Brand/Details/5

        public ActionResult Details(int id = 0)
        {
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        //
        // GET: /Brand/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Brand/Create

        [HttpPost]
        public ActionResult Create(Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Brands.Add(brand);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(brand);
        }

        //
        // GET: /Brand/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        //
        // POST: /Brand/Edit/5

        [HttpPost]
        public ActionResult Edit(Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        //
        // GET: /Brand/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        //
        // POST: /Brand/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Brand brand = db.Brands.Find(id);
            db.Brands.Remove(brand);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcStore/MvcStore/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStore.Models;

namespace MvcStore.Controllers
{
    //[Authorize(Roles = "Administrator")]
    public class ModelController : Controller
    {
        private CopierStoreEntities db = new CopierStoreEntities();

        //
        // GET: /Model/

        public ActionResult Index()
        {
            var models = db.Models.Include(m => m.Brand).Include(m => m.Toner).Include(m => m.Supplier);
            return View(models.ToList());
        }

        //
        // GET: /Model/Details/5

        public ActionResult Details(int id = 0)
        {
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        //
        // GET: /Model/Create

        public ActionResult Create()
        {
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name");
            ViewBag.TonerId = new SelectList(db.Toners, "TonerId", "Name");
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "Name");
            return View();
        }

        //
        // POST: /Model/Create

        [HttpPost]
        public ActionResult Create(Model model)
        {
            if (ModelState.IsValid)
            {
                db.Models.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name", model.BrandId);
            ViewBag.TonerId = new SelectList(db.Toners, "TonerId", "Name", model.TonerId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "Name", model.SupplierId);
            return View(model);
        }

        //
        // GET: /Model/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name", model.BrandId);
            ViewBag.TonerId = new SelectList(db.Toners, "TonerId", "Name", model.TonerId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "Name", model.SupplierId);
            return View(model);
        }

        //
        // POST: /Model/Edit/5

        [HttpPost]
        public ActionResult Edit(Model model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "Name", model.BrandId);
            ViewBag.TonerId = new SelectList(db.Toners, "TonerId", "Name", model.TonerId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "Name", model.SupplierId);
            return View(model);
        }

        //
        // GET: /Model/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        //
        // POST: /Model/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Model model = db.Models.Find(id);
            db.Models.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcStore/MvcStore/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStore.Models;

namespace MvcStore.Controllers
{
    public class UserController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /User/

        public ActionResult Index()
        {
            return View(db.UserProfiles.ToList());
        }

        //
        // GET: /User/Details/5

        public ActionResult Details(int id = 0)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

      
        //
        // GET: /User/Edit/5

        public ActionResult Edit(int id = 0)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // POST: /User/Edit/5

        [HttpPost]
        public ActionResult Edit(UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userprofile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userprofile);
        }

        //
        // GET: /User/Delete/5

        public ActionResult Delete(int id = 0)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // POST: /User/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            db.UserProfiles.Remove(userprofile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcStore/MvcStore/Views/Brand/BrandMenu.cshtml
@{
    ViewBag.Title = "BrandMenu";
}

<ul class="nav nav-tabs nav-stacked">
    <li>@Html.ActionLink("Store Manager", "Index", "StoreManager")</li>
    <li>@Html.ActionLink("Product", "Index", "Model")</li>
    <li>@Html.ActionLink("Cartidage", "Index", "Toner")</li>
    <li>@Html.ActionLink("Supplier", "Index", "Supplier")</li>
    <li>@Html.ActionLink("Users", "Index", "User")</li>
</ul>

MvcStore/MvcStore/Views/Brand/Create.cshtml
@model MvcStore.Models.Brand

@{
    ViewBag.Title = "Create";
}

<h2>Add New Brand</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Brand</legend>

        <table>
            <tr>
                <td>@Html.LabelFor(model => model.Name)</td>
                <td>
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Description)</td>
                <td>
                      @Html.TextAreaFor(model => model.Description, new { @style = "resize:none; width:300px; height:150px;"})
                    @Html.ValidationMessageFor(model => model.Description)
                </td>
            </tr>
        </table>

        <p>
            <input class="btn btn-warning" type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcStore/MvcStore/Views/Brand/Delete.cshtml
@model MvcStore.Models.Brand

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Confirmation</h2>

<h3>Are you sure you want to delete @Html.DisplayFor(model => model.Name)?</h3>

@using (Html.BeginForm()) {
    <p>
        <input class="btn btn-warning" type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcStore/MvcStore/Views/Brand/Details.cshtml
@model MvcStore.Models.Brand

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Brand</legend>
    <table class="tablesorter">
        <thead>
             <th>Name</th>
             <th>Description</th>
        </thead>
        <tbody>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Name)</td>
                <td>
                    @Html.DisplayFor(model => model.Name)
                </td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Description)</td>
                <td>
                    @Html.DisplayFor(model => model.Description)
                </td>
            </tr>
        </tbody>
    </table>

</fieldset>
<br />
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.BrandId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcStore/MvcStore/Views/Brand/Edit.cshtml
@model MvcStore.Models.Brand

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Brand</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Brand</legend>

        @Html.HiddenFor(model => model.BrandId)

        <table>
            <tr>
                <td>@Html.LabelFor(model => model.Name)</td>
                <td>

                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Description)</td>
                <td>

                    @Html.EditorFor(model => model.Description)
                    @Html.ValidationMessageFor(model => model.Description)
                </td>
            </tr>
        </table>

        <p>
            <input class="btn btn-warning" type="submit" value="Save" />
        </p>
    </fieldset>
}
<br />
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcStore/MvcStore/Views/Brand/Index.cshtml
@model IEnumerable<MvcStore.Models.Brand>

@{
    ViewBag.Title = "Index";
}

<div class="container-fluid">
    <div class="row-fluid">

        <div class="span2">
            @Html.Partial("~/Views/Brand/BrandMenu.cshtml")
        </div>

        <div class="span10">
            <p>
                @Html.ActionLink("Create New", "Create")
            </p>
            <table class="tablesorter">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.BrandId }) |
                            @Html.ActionLink("Details", "Details", new { id = item.BrandId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.BrandId })
                        </td>
                    </tr>
                }

            </table>

        </div>
    </div>
</div>